name: hugo rsync
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Build API page
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: "bundle --options.disableGoogleFont=true content/api/openapi.yaml -o public/api/index.html"

      - name: Push to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: deploy

      - name: checkout deploy
        run: git checkout -f deploy

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          path: public/
          remote_path: /home/docs/Websites/trueblocks.io
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.HOST_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Report job status
        run: |
          echo "This job's status is ${{ job.status }}"
