name: Check links on site
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
jobs:
  run_linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: checkout deploy
        run: sleep 3m; git checkout deploy
      
      - name: Install linkinator
        run: npm install -g linkinator

      # Don't put this on a single line. GitHub runner doesn't like that
      - name: check links
        run: pwd && ls -l && linkinator -r index.html docs/ papers/ data-model/ api/ --skip localhost:23456 --skip tokenomics.io --skip etherscan.io
